insert into top_secret_data (client_id,client_secret,naziv_casopisa)
values ("Ae_29b_0t76NauXNqN2GpLBl7CAR82-AoEOGpn4OpY29CBNLDVdD4QwKdheDsBHafoQvs_HLnCRGYSbm","EBtg38K9znkZNdNgrib5mZDdifDYzMqVYHLybGuaftjFd8Q76ag5tjZuxytET2DczXDXxWBP-vp2c97K","Top Speed");
insert into top_secret_data (client_id,client_secret,naziv_casopisa)
values ("AdOdayvE1hr6X-iNk_ja5XialfwqRhawFmxt9UlKKIeI1pr1S2ZsaH0jO7osUH1niA2mdGncKxxOz8K3","EPcFcbQoKgkJx5c7VrfZWi1NkZfRjTRj0WvABsxNsn6_FmhBI3xgK3wowFHbUUf4RHaWXUEU9RQ_7Qaw","Casopis");
